---
abstract: 'Easy Validation Handler'
author:
  - 'Torsten Raudssus <torsten@raudss.us>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Syccess
requires:
  Module::Load::Conditional: '0'
  Module::Runtime: '0'
  Moo: '0'
  MooX::Traits: '0'
  Scalar::Util: '0'
  Tie::IxHash: '0'
resources:
  homepage: https://github.com/SyContent/Syccess
  repository: https://github.com/SyContent/Syccess.git
version: '0.103'
x_Dist_Zilla:
  perl:
    version: '5.018001'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::GETTY/Git::GatherDir'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::GETTY/@Filter/PruneCruft'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::GETTY/@Filter/ManifestSkip'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::GETTY/@Filter/MetaYAML'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::GETTY/@Filter/License'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::GETTY/@Filter/Readme'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::GETTY/@Filter/ExtraTests'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::GETTY/@Filter/ExecDir'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::GETTY/@Filter/ShareDir'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::GETTY/@Filter/MakeMaker'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::GETTY/@Filter/Manifest'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::GETTY/@Filter/TestRelease'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::GETTY/@Filter/ConfirmRelease'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::GETTY/@Filter/UploadToCPAN'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: '0'
          version_regexp: (?^:^([0-9]+\.[0-9]+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::GETTY/Git::NextVersion'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::GETTY/PkgVersion'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::GETTY/MetaConfig'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::GETTY/MetaJSON'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::GETTY/PodSyntaxTests'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::GETTY/GithubMeta'
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::TravisCI
      name: '@Author::GETTY/TravisCI'
      version: '0.005'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::GETTY/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::GETTY/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::GETTY/Git::CheckFor::CorrectBranch'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Prereqs::FromCPANfile
      name: '@Author::GETTY/Prereqs::FromCPANfile'
      version: '0.06'
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@Author::GETTY/ChangelogFromGit'
      version: '0.016'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@Author::GETTY'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@GETTY/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@GETTY/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@GETTY/Prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Synopsis'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Description'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Overview'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: '@GETTY/Stability'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: Attributes
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: Methods
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: Functions
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@GETTY/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@GETTY/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Bugs
              name: '@GETTY/Bugs'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: '@GETTY/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: '@GETTY/Legal'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@GETTY/List'
              version: '4.006'
      name: '@Author::GETTY/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::GETTY/@Git/Check'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::GETTY/@Git/Commit'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: '0.103'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::GETTY/@Git/Tag'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::GETTY/@Git/Push'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.029'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.029'
x_authority: cpan:GETTY
